version: '3.1'

name: lin-iapi
services:
  db:
    container_name: lin-iapi-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  web:
    container_name: lin-iapi-web
    build: 
      context: .
    volumes:
      - ..:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db